import { AGENT_PROFILES, type AppLanguage } from '../agent/profiles';

export interface HomeState {
  projectId?: string;
  displayName?: string;
  experience?: 'guided' | 'balanced' | 'concise';
  accent?: 'sage' | 'ocean' | 'clay';
  brief?: { goal: string; audience: string; criteria: string[]; kind: 'web' | 'app' | 'automation' | 'learn' | 'other'; updatedAt?: number };
  modelLabel?: string;
  local?: boolean;
}
const escape = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const json = (value: unknown) => JSON.stringify(value).replaceAll('<', '\\u003c').replaceAll('>', '\\u003e').replaceAll('&', '\\u0026').replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029');

export function renderHome(nonce: string, language: AppLanguage, project?: string, state: HomeState = {}): string {
  if (!/^[A-Za-z0-9+/_=-]{16,128}$/.test(nonce)) throw new Error('Invalid nonce');
  const say = (es: string, en: string) => language === 'en' ? en : es;
  const t = (es: string, en: string) => escape(say(es, en));
  const agents = AGENT_PROFILES.map((profile, index) => `<button class="agent" data-action="profile" data-profile="${profile.id}"><span class="index">0${index + 1}</span><strong>${escape(profile.name[language])}</strong><small>${escape(profile.description[language])}</small></button>`).join('');
  const starters = [
    { title: say('Mi página personal', 'My personal website'), detail: say('Tu trabajo, con tu voz.', 'Your work, in your words.'), kind: 'web', goal: say('Crear una página personal para presentar mi trabajo y facilitar que me contacten.', 'Create a personal website to present my work and make it easy to contact me.'), audience: say('Personas interesadas en mi trabajo.', 'People interested in my work.'), criteria: [say('Se lee bien en móvil y ordenador.', 'It reads well on mobile and desktop.'), say('Puedo cambiar el contenido fácilmente.', 'I can easily update the content.')] },
    { title: say('Una herramienta útil', 'A useful little tool'), detail: say('Resuelve algo de tu día.', 'Solve something in your day.'), kind: 'app', goal: say('Crear una lista de tareas sencilla que guarde mis pendientes en este dispositivo.', 'Create a simple to-do list that saves my tasks on this device.'), audience: say('Personas que buscan organizarse.', 'People who want to stay organized.'), criteria: [say('Puedo añadir, completar y borrar tareas.', 'I can add, complete and delete tasks.'), say('Las tareas siguen ahí al volver a abrirla.', 'Tasks are still there when I reopen it.')] },
    { title: say('Menos tareas repetidas', 'Less repetitive work'), detail: say('Empieza por un paso pequeño.', 'Start with one small step.'), kind: 'automation', goal: say('Listar archivos de una carpeta y proponer cómo organizarlos antes de mover nada.', 'List files in a folder and suggest how to organize them before moving anything.'), audience: say('Personas que quieren ordenar sus archivos.', 'People who want to organize their files.'), criteria: [say('Muestra una vista previa de los cambios.', 'Shows a preview of the changes.'), say('No mueve ni elimina archivos sin mi permiso.', 'Does not move or delete files without my permission.')] },
    { title: say('Aprender construyendo', 'Learn by building'), detail: say('Una idea, una explicación.', 'One idea, one explanation.'), kind: 'learn', goal: say('Aprender a crear una página web sencilla entendiendo cada parte con ejemplos pequeños.', 'Learn to create a simple web page through small examples that explain each part.'), audience: say('Yo; estoy empezando a programar.', 'Me; I am new to programming.'), criteria: [say('Cada paso explica qué cambia y por qué.', 'Each step explains what changes and why.'), say('Puedo probar el resultado de cada paso.', 'I can try the result of each step.')] },
  ];
  const strings = {
    draft: say('Cambios sin guardar', 'Unsaved changes'), saved: say('Guardado en este proyecto', 'Saved in this project'), empty: say('Tu cuaderno está listo para empezar', 'Your notebook is ready to start'),
    waiting: say('Guardando…', 'Saving…'), uncertain: say('No llegó la confirmación. Tu borrador se conserva; vuelve a intentarlo.', 'No confirmation arrived. Your draft is preserved; try again.'),
    goal: say('Escribe primero qué quieres conseguir.', 'First describe what you want to achieve.'), folder: say('Abre o crea una carpeta para guardar este cuaderno y preparar un paso.', 'Open or create a folder to save this notebook and prepare a step.'),
    limits: say('Usa hasta 8 criterios, de 300 caracteres cada uno.', 'Use up to 8 criteria, each with 300 characters.'), replaced: say('Idea preparada. Puedes cambiar todos los detalles antes de guardar.', 'Idea prepared. You can change every detail before saving.'),
    welcome: say('Tu espacio para crear.', 'Your space to create.'), greeting: say('Vamos a crear, ', 'Let’s create, '), later: say('Guardado. También tienes cambios posteriores sin guardar.', 'Saved. You also have newer unsaved changes.'),
  };
  const initial = { project: project ?? '', identity: state.projectId ?? project ?? '', displayName: state.displayName ?? '', experience: state.experience ?? 'guided', accent: state.accent ?? 'sage', brief: state.brief ?? { goal: '', audience: '', criteria: [], kind: 'other' }, strings, starters };
  const journey = (step: string, number: string, title: string, detail: string) => `<button class="journey" data-journey="${step}"><span class="index">${number}</span><span><strong>${title}</strong><small>${detail}</small></span><span class="arrow" aria-hidden="true">↗</span></button>`;
  return `<!doctype html><html lang="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'; base-uri 'none'; form-action 'none';"><title>Caled · ${t('Mi estudio', 'My studio')}</title>
<style nonce="${nonce}">
:root{color-scheme:light dark;--fg:var(--vscode-editor-foreground,#dae0db);--muted:var(--vscode-descriptionForeground,#a9b4ad);--line:var(--vscode-panel-border,#39453e);--surface:var(--vscode-sideBar-background,#202623);--accent:#96c9ad}
*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;background:var(--vscode-editor-background,#171b1a);color:var(--fg);font:14px/1.6 "Segoe UI Variable","Segoe UI",system-ui,sans-serif}
body.vscode-light,body.vscode-high-contrast-light{color-scheme:light}body.vscode-dark,body.vscode-high-contrast{color-scheme:dark}
body[data-accent="ocean"]{--accent:#9cc6e0}body[data-accent="clay"]{--accent:#e3b09a}body.vscode-light{--accent:#32654c}body.vscode-light[data-accent="ocean"]{--accent:#235d82}body.vscode-light[data-accent="clay"]{--accent:#8a4b32}body.vscode-high-contrast[data-accent],body.vscode-high-contrast-light[data-accent]{--accent:var(--vscode-textLink-foreground)}
button,input,textarea,select{font:inherit}button{color:inherit;cursor:pointer;min-height:42px;border:1px solid var(--line);background:transparent;border-radius:5px;padding:9px 16px}button:disabled{opacity:.6;cursor:wait}button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:2px solid var(--vscode-focusBorder,var(--accent));outline-offset:4px}button:hover{background:var(--vscode-list-hoverBackground,#29312d)}.primary{color:var(--vscode-button-foreground);background:var(--vscode-button-background);border-color:transparent}.primary:hover{background:var(--vscode-button-hoverBackground)}
main{max-width:1180px;margin:auto;padding:26px clamp(22px,5vw,64px) 36px}header{display:flex;align-items:center;gap:16px}.brand{display:flex;align-items:center;gap:10px;font-weight:600;font-size:27px;letter-spacing:-1px}.brand svg{width:32px;height:32px;color:var(--accent)}.edition{padding-left:16px;border-left:1px solid var(--line);color:var(--muted);font-size:12px}.tools{display:flex;gap:8px;margin-left:auto}.quiet{border-color:transparent;color:var(--muted);font-size:12px;padding:8px 10px}
.navigation{display:flex;align-items:center;gap:12px;margin:24px 0 0;border-bottom:1px solid var(--line)}[role="tablist"]{display:flex;gap:25px}[role="tab"]{padding:12px 0;border:0;border-bottom:2px solid transparent;border-radius:0;color:var(--muted)}[role="tab"][aria-selected="true"]{border-bottom-color:var(--accent);color:var(--fg);font-weight:600}.engine{display:flex;align-items:center;gap:7px;margin-left:auto;font-size:11px;color:var(--muted)}.dot{width:6px;height:6px;border-radius:50%;background:var(--accent)}.section{padding-top:34px}
.eyebrow{color:var(--accent);text-transform:uppercase;letter-spacing:1.6px;font:11px/1.6 "Segoe UI",sans-serif;margin:0 0 12px}h1{font-size:clamp(30px,4.6vw,48px);font-weight:550;letter-spacing:-1.7px;line-height:1.15;margin:0 0 18px;max-width:600px}h2{font-size:18px;letter-spacing:-.4px;font-weight:600;margin:0}p{margin:0}.lead,.note,small{color:var(--muted)}.lead{max-width:520px;font-size:15px}.note{font-size:12px}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:22px}.hero{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(215px,1fr);gap:34px;align-items:center}
.session{padding:19px 20px;border:1px solid var(--line);border-top:2px solid var(--accent);border-radius:2px}.session-row{padding:13px 0;border-bottom:1px solid var(--line)}.session-row:last-child{padding-bottom:0;border-bottom:0}.session-row strong{display:block;font-weight:500;overflow-wrap:anywhere;margin-top:3px}.model-button{text-align:left;border:0;padding:0;min-height:35px;max-width:100%;overflow-wrap:anywhere;color:var(--accent)}
.section-heading{display:flex;gap:12px;align-items:baseline;flex-wrap:wrap;margin:34px 0 15px}.starters{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border:1px solid var(--line);border-radius:5px;overflow:hidden}.starter{border:0;border-right:1px solid var(--line);border-radius:0;padding:17px;text-align:left;display:flex;flex-direction:column;gap:6px}.starter:last-child{border-right:0}.starter .arrow{color:var(--accent);margin-bottom:7px}.starter strong{font-weight:600}.starter small{font-size:12px;line-height:1.5}
.journeys{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:17px}.journey{display:flex;align-items:flex-start;gap:11px;padding:16px 12px;text-align:left}.index{color:var(--accent);font:11px/1.6 Consolas,monospace}.journey strong{display:block;font-size:13px;font-weight:600}.journey small{display:block;font-size:12px;margin-top:5px;line-height:1.5}.arrow{margin-left:auto;color:var(--accent)}.agents{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.agent{display:flex;flex-direction:column;gap:8px;text-align:left;padding:14px}.agent strong{font-weight:600}.agent small{font-size:11px;line-height:1.55}
.project-header{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:24px}.project-header h1{font-size:32px;margin-bottom:8px}.badge{font-size:11px;border:1px solid var(--line);border-radius:3px;padding:5px 9px;white-space:nowrap;color:var(--muted)}.notebook{border:1px solid var(--line);border-left:3px solid var(--accent);border-radius:3px;padding:26px}.paper-top{display:flex;justify-content:space-between;gap:10px;padding-bottom:18px;border-bottom:1px solid var(--line);margin-bottom:20px}.paper-top .eyebrow{margin:0}label,legend{font-weight:600}.field{display:flex;flex-direction:column;gap:8px;margin-bottom:22px}.field:last-child{margin-bottom:0}.label-row{display:flex;justify-content:space-between;align-items:baseline;gap:12px}.counter{color:var(--muted);font-size:11px;font-weight:400;font-variant-numeric:tabular-nums}
input[type="text"],textarea,select{width:100%;color:var(--vscode-input-foreground,var(--fg));background:var(--vscode-input-background,var(--surface));border:1px solid var(--vscode-input-border,var(--line));border-radius:3px;padding:10px 12px}textarea{resize:vertical;min-height:90px;line-height:1.65}textarea::placeholder,input::placeholder{color:var(--vscode-input-placeholderForeground,var(--muted))}#goal{font-size:17px;min-height:112px}.row{display:grid;grid-template-columns:1fr 1fr;gap:22px}.form-footer{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-top:20px}.folder-note,.replacement{border:1px solid var(--line);padding:16px 18px;margin-bottom:20px;border-radius:4px;background:var(--surface)}.replacement .actions,.folder-note .actions{margin-top:12px}.status{margin:20px 0 0;min-height:24px;font-size:12px;color:var(--accent)}.status[data-error="true"]{color:var(--vscode-errorForeground)}.spaced{margin-top:12px}
fieldset{border:0;padding:0;margin:0 0 27px;min-width:0}legend{margin-bottom:12px;padding:0}.preferences-grid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(200px,1fr);gap:28px}.choice{display:flex;align-items:flex-start;gap:12px;padding:13px 14px;border:1px solid var(--line);border-radius:4px;margin-bottom:8px;cursor:pointer;font-weight:400}.choice:has(input:checked){border-color:var(--accent);background:var(--vscode-list-inactiveSelectionBackground)}input[type="radio"]{accent-color:var(--accent);margin-top:5px;width:16px;height:16px;flex-shrink:0}.choice strong{display:block;font-weight:600}.choice small{display:block;font-size:12px;margin-top:3px}.accents{display:flex;flex-wrap:wrap;gap:8px}.accents .choice{align-items:center;margin:0;padding:10px}.accents input{margin:0}.swatch{width:13px;height:13px;border-radius:50%;border:1px solid currentColor}.sage{background:#7cbea0}.ocean{background:#83b6d3}.clay{background:#d49e86}.preview{background:var(--surface);border:1px solid var(--line);border-top:3px solid var(--accent);padding:24px;align-self:start}.preview-mark{font-size:45px;font-weight:500;letter-spacing:-3px;color:var(--accent);line-height:1;margin:18px 0 28px}.preview h2{font-size:24px;line-height:1.3;margin-bottom:12px;overflow-wrap:anywhere}
footer{display:flex;flex-wrap:wrap;justify-content:space-between;gap:10px;color:var(--muted);font-size:11px;margin-top:28px;padding-top:18px;border-top:1px solid var(--line)}
@media(max-width:850px){.agents{grid-template-columns:repeat(3,minmax(0,1fr))}.hero{gap:22px}.journeys{grid-template-columns:1fr;gap:8px}.journey{align-items:center}.journey small{margin-top:0}.starters{grid-template-columns:repeat(2,minmax(0,1fr))}.starter:nth-child(2){border-right:0}.starter:nth-child(-n+2){border-bottom:1px solid var(--line)}}
@media(max-width:620px){main{padding:20px}.hero,.preferences-grid,.row{grid-template-columns:1fr}.edition{display:none}.tools{gap:0}.tools button{font-size:11px}.engine{display:none}.navigation{margin-top:18px}[role="tablist"]{width:100%;justify-content:space-between;gap:12px}.section{padding-top:26px}.session{padding:12px 18px}.agents{grid-template-columns:repeat(2,minmax(0,1fr))}.notebook{padding:18px}.project-header,.form-footer{flex-wrap:wrap}.preview{display:none}}
@media(forced-colors:active){.choice:has(input:checked),[role="tab"][aria-selected="true"]{outline:1px solid Highlight}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
</style></head><body data-accent="${escape(initial.accent)}"><main>
<header><div class="brand"><svg viewBox="0 0 64 64" aria-hidden="true" fill="none"><path d="M46 17a21 21 0 1 0 0 30" stroke="currentColor" stroke-width="7" stroke-linecap="round"/><path d="M30 32h26m-7-7 7 7-7 7" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></svg>caled</div><span class="edition">${t('Mi estudio', 'My studio')}</span><div class="tools"><button class="quiet" data-action="preferences">${t('Idioma y tema', 'Language & theme')}</button><button class="quiet" data-action="account">${t('Cuenta', 'Account')}</button></div></header>
<div class="navigation"><nav role="tablist" aria-label="${t('Mi estudio', 'My studio')}"><button id="tab-home" role="tab" aria-controls="section-home" aria-selected="true" data-tab="home">${t('Inicio', 'Home')}</button><button id="tab-project" role="tab" aria-controls="section-project" aria-selected="false" tabindex="-1" data-tab="project">${t('Proyecto', 'Project')}</button><button id="tab-space" role="tab" aria-controls="section-space" aria-selected="false" tabindex="-1" data-tab="space">${t('Mi espacio', 'My space')}</button></nav><span class="engine"><span class="dot" aria-hidden="true"></span>${state.local ? t('Modelo local seleccionado', 'Local model selected') : t('Tu modelo, tu elección', 'Your model, your choice')}</span></div>
<section class="section" id="section-home" role="tabpanel" aria-labelledby="tab-home"><div class="hero"><div><p class="eyebrow">${t('De la idea al primer paso', 'From idea to first step')}</p><h1 id="greeting">${state.displayName ? t('Vamos a crear, ', 'Let’s create, ') + escape(state.displayName) + '.' : t('Tu espacio para crear.', 'Your space to create.')}</h1><p class="lead">${t('Dale forma a tu idea en un cuaderno. Prepara el siguiente paso con la ayuda que necesitas.', 'Shape your idea in a notebook. Prepare the next step with the help you need.')}</p><div class="actions"><button class="primary" data-go="project">${state.brief?.goal ? t('Volver a mi cuaderno', 'Back to my notebook') : t('Escribir mi idea', 'Write my idea')}</button><button data-action="assistant">${t('Abrir asistente', 'Open assistant')}</button></div></div><aside class="session" aria-label="${t('Tu sesión', 'Your session')}"><p class="eyebrow">${t('Sobre tu mesa', 'On your desk')}</p><div class="session-row"><span class="note">${t('Proyecto abierto', 'Open project')}</span><strong>${project ? escape(project) : t('Aún sin carpeta', 'No folder yet')}</strong></div><div class="session-row"><span class="note">${t('Modelo elegido', 'Selected model')}</span><br><button class="model-button" data-action="models">${state.modelLabel ? escape(state.modelLabel) : t('Elegir un modelo', 'Choose a model')} ↗</button></div><div class="session-row"><button class="quiet" data-action="${project ? 'openFolder' : 'createProject'}">${project ? t('Cambiar de proyecto', 'Switch project') : t('Crear mi primer proyecto', 'Create my first project')} ↗</button></div></aside></div>
<div class="section-heading"><h2>${t('Una idea para empezar', 'A starting point')}</h2><p class="note">${t('Son borradores. Hazlos tuyos.', 'These are drafts. Make them yours.')}</p></div><div class="starters">${starters.map((starter, index) => `<button class="starter" data-starter="${index}"><span class="arrow" aria-hidden="true">↗</span><strong>${escape(starter.title)}</strong><small>${escape(starter.detail)}</small></button>`).join('')}</div>
<div class="section-heading"><h2>${t('La ayuda adecuada', 'The right kind of help')}</h2><p class="note">${t('5 perfiles · una tarea a la vez', '5 profiles · one task at a time')}</p></div><div class="agents">${agents}</div></section>
<section class="section" id="section-project" role="tabpanel" aria-labelledby="tab-project" hidden><div class="project-header"><div><p class="eyebrow">${t('Cuaderno de proyecto', 'Project notebook')}</p><h1>${t('Primero, lo que importa.', 'First, what matters.')}</h1><p class="note">${t('Un objetivo claro ayuda a la IA a trabajar contigo.', 'A clear goal helps AI work with you.')}</p></div><span class="badge">${project ? escape(project) : t('Borrador sin carpeta', 'Draft without a folder')}</span></div>
${project ? '' : `<div class="folder-note"><p>${t('Puedes escribir tu idea aquí. Para guardar el cuaderno y preparar un paso, abre o crea una carpeta de proyecto.', 'You can write your idea here. To save the notebook and prepare a step, open or create a project folder.')}</p><div class="actions"><button data-action="createProject">${t('Crear un proyecto', 'Create a project')}</button><button data-action="openFolder">${t('Abrir un proyecto', 'Open a project')}</button></div><p class="note">${t('El borrador de esta ventana no se traslada automáticamente a otra carpeta.', 'This window’s draft is not automatically transferred to another folder.')}</p></div>`}
<div class="replacement" id="replacement" hidden role="region" aria-label="${t('Reemplazar borrador', 'Replace draft')}"><strong>${t('Ya tienes una idea en el cuaderno.', 'You already have an idea in your notebook.')}</strong><p class="note">${t('La propuesta reemplazará los campos. El cuaderno guardado se conserva hasta que guardes de nuevo.', 'The suggestion will replace the fields. Your saved notebook stays unchanged until you save again.')}</p><div class="actions"><button id="replace-starter">${t('Reemplazar borrador', 'Replace draft')}</button><button id="cancel-starter">${t('Conservar mi idea', 'Keep my idea')}</button></div></div>
<form id="brief-form"><div class="notebook"><div class="paper-top"><p class="eyebrow">${t('01 / Tu intención', '01 / Your intention')}</p><span class="note">${t('Se guarda en este equipo', 'Saved on this device')}</span></div><div class="field"><div class="label-row"><label for="goal">${t('¿Qué quieres conseguir?', 'What do you want to achieve?')}</label><span class="counter" id="goal-count">0 / 2000</span></div><textarea id="goal" maxlength="2000" rows="3" placeholder="${t('Quiero crear… para poder…', 'I want to create… so that…')}" aria-describedby="goal-count"></textarea></div><div class="row"><div class="field"><label for="kind">${t('Tipo de proyecto', 'Project type')}</label><select id="kind"><option value="other">${t('Todavía lo estoy pensando', 'Still figuring it out')}</option><option value="web">${t('Página web', 'Website')}</option><option value="app">${t('Aplicación', 'Application')}</option><option value="automation">${t('Automatización', 'Automation')}</option><option value="learn">${t('Aprender', 'Learning')}</option></select></div><div class="field"><label for="audience">${t('¿Para quién?', 'Who is it for?')}</label><input type="text" id="audience" maxlength="500" placeholder="${t('Para mí, mis clientes, mi equipo…', 'Me, my customers, my team…')}"></div></div><div class="field"><label for="criteria">${t('Sabré que funciona cuando…', 'I will know it works when…')}</label><textarea id="criteria" rows="3" maxlength="2407" aria-describedby="criteria-help" placeholder="${t('Pueda usarlo desde el móvil.\nLos datos se conserven al volver.', 'I can use it on my phone.\nMy data is still there when I return.')}"></textarea><span class="note" id="criteria-help">${t('Una comprobación por línea. Hasta 8, de 300 caracteres cada una.', 'One check per line. Up to 8, each with 300 characters.')}</span></div></div><div class="form-footer"><p id="brief-state" class="note" aria-live="polite"></p><button class="primary" type="submit" id="save-brief">${t('Guardar cuaderno', 'Save notebook')}</button></div></form>
<div class="section-heading"><h2>${t('Elige tu siguiente paso', 'Choose your next step')}</h2></div><div class="journeys">${journey('plan', '01', t('Entender y planear', 'Understand & plan'), t('El Guía prepara un plan.', 'The Guide prepares a plan.'))}${journey('build', '02', t('Construir una parte', 'Build one part'), t('El Constructor propone cambios.', 'The Builder proposes changes.'))}${journey('check', '03', t('Comprobar el resultado', 'Check the result'), t('El Verificador prepara pruebas.', 'The Tester prepares checks.'))}</div><p class="note spaced">${t('Cada paso guarda el cuaderno y prepara una instrucción en el asistente. Revísala y envíala cuando quieras empezar; pulsar aquí no ejecuta la IA.', 'Each step saves the notebook and prepares an instruction in the assistant. Review and send it when you want to start; clicking here does not run AI.')}</p></section>
<section class="section" id="section-space" role="tabpanel" aria-labelledby="tab-space" hidden><div class="project-header"><div><p class="eyebrow">${t('Hecho a tu manera', 'Made your way')}</p><h1>${t('Un espacio que se siente tuyo.', 'A space that feels like yours.')}</h1><p class="note">${t('Estas preferencias se guardan en este equipo, sin crear una cuenta.', 'These preferences are saved on this device, without creating an account.')}</p></div></div><div class="preferences-grid"><form id="personal-form"><div class="field"><label for="display-name">${t('¿Cómo te llamamos?', 'What should we call you?')}</label><input id="display-name" type="text" maxlength="40" autocomplete="off" placeholder="${t('Tu nombre, si quieres', 'Your name, if you like')}"></div><fieldset><legend>${t('Cómo quieres que te expliquemos', 'How you want things explained')}</legend>${(['guided', 'balanced', 'concise'] as const).map((value, index) => `<label class="choice"><input type="radio" name="experience" value="${value}"><span><strong>${[t('Con guía', 'Guided'), t('Equilibrado', 'Balanced'), t('Directo', 'Concise')][index]}</strong><small>${[t('Pasos pequeños, ejemplos y explicación de los términos.', 'Small steps, examples and explanations of unfamiliar terms.'), t('El contexto necesario y una propuesta concreta.', 'The context you need and a concrete proposal.'), t('Respuestas breves, centradas en la acción y el resultado.', 'Brief answers focused on the action and result.')][index]}</small></span></label>`).join('')}</fieldset><fieldset><legend>${t('Tu color de acento', 'Your accent color')}</legend><div class="accents">${(['sage', 'ocean', 'clay'] as const).map((value, index) => `<label class="choice"><input type="radio" name="accent" value="${value}"><span class="swatch ${value}" aria-hidden="true"></span><span>${[t('Salvia', 'Sage'), t('Océano', 'Ocean'), t('Arcilla', 'Clay')][index]}</span></label>`).join('')}</div><p class="note spaced">${t('El acento acompaña al tema claro, oscuro o del sistema.', 'Your accent works with the light, dark or system theme.')}</p></fieldset><button class="primary" id="save-personal" type="submit">${t('Guardar mi espacio', 'Save my space')}</button><button class="quiet" type="button" data-action="preferences">${t('Cambiar idioma o tema', 'Change language or theme')} ↗</button></form><aside class="preview"><p class="eyebrow">${t('Vista previa', 'Preview')}</p><div class="preview-mark" aria-hidden="true">c↗</div><h2 id="preview-name">${t('Tu espacio para crear.', 'Your space to create.')}</h2><p class="note">${t('Tu estilo de explicación se utiliza en las conversaciones y en las instrucciones del agente.', 'Your explanation style is used in conversations and agent instructions.')}</p></aside></div></section>
<p id="status" class="status" role="status" aria-live="polite" aria-atomic="true"></p><footer><span>${t('IA local sin cuota por token. Sin cuenta obligatoria.', 'Local AI with no per-token fee. No account required.')}</span><span>${t('Tú decides qué se aplica.', 'You choose what gets applied.')}</span></footer>
</main><script nonce="${nonce}">
const initial=${json(initial)};
const vscode=acquireVsCodeApi();
const byId=id=>document.getElementById(id);
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const cleanBrief=value=>({goal:typeof value?.goal==='string'?value.goal.slice(0,2000):'',audience:typeof value?.audience==='string'?value.audience.slice(0,500):'',criteria:Array.isArray(value?.criteria)?value.criteria.filter(v=>typeof v==='string').map(v=>v.slice(0,300)).slice(0,8):[],kind:['web','app','automation','learn','other'].includes(value?.kind)?value.kind:'other'});
const cleanPersonal=value=>({displayName:typeof value?.displayName==='string'?value.displayName.slice(0,40):'',experience:['guided','balanced','concise'].includes(value?.experience)?value.experience:'guided',accent:['sage','ocean','clay'].includes(value?.accent)?value.accent:'sage'});
let cached;try{cached=vscode.getState();}catch{};
if(!cached||cached.identity!==initial.identity)cached={};
let savedBrief=cleanBrief(initial.brief),savedPersonal=cleanPersonal(initial);
let currentTab=['home','project','space'].includes(cached.tab)?cached.tab:'home';
let pending=cached.pending&&typeof cached.pending.id==='string'&&['saveBrief','journey','personalize','profile'].includes(cached.pending.action)?cached.pending:undefined;
let pendingTimer,starter;
const brief=()=>({goal:byId('goal').value,audience:byId('audience').value,criteria:byId('criteria').value.split(/\\r?\\n/).map(value=>value.trim()).filter(Boolean),kind:byId('kind').value});
const personal=()=>({displayName:byId('display-name').value,experience:document.querySelector('input[name="experience"]:checked')?.value||'guided',accent:document.querySelector('input[name="accent"]:checked')?.value||'sage'});
function persist(){vscode.setState({identity:initial.identity,tab:currentTab,brief:brief(),criteriaText:byId('criteria').value,personal:personal(),pending});}
function status(message,error=false){byId('status').textContent=message;byId('status').dataset.error=String(error);}
function update(){const value=brief();byId('goal-count').textContent=value.goal.length+' / 2000';byId('brief-state').textContent=!same(value,savedBrief)?initial.strings.draft:value.goal||value.audience||value.criteria.length?initial.strings.saved:initial.strings.empty;const person=personal();byId('preview-name').textContent=person.displayName.trim()?initial.strings.greeting+person.displayName.trim()+'.':initial.strings.welcome;document.body.dataset.accent=person.accent;persist();}
function fillBrief(value){byId('goal').value=value.goal;byId('audience').value=value.audience;byId('criteria').value=value.criteria.join('\\n');byId('kind').value=value.kind;}
function tab(value,focus=false){if(!['home','project','space'].includes(value))return;currentTab=value;document.querySelectorAll('[data-tab]').forEach(button=>{const selected=button.dataset.tab===value;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;if(selected&&focus)button.focus();});['home','project','space'].forEach(key=>byId('section-'+key).hidden=key!==value);persist();}
function busy(){document.querySelectorAll('#save-brief,#save-personal,[data-journey],[data-action="profile"]').forEach(button=>button.disabled=Boolean(pending));}
function armTimeout(){clearTimeout(pendingTimer);if(!pending)return;const id=pending.id;pendingTimer=setTimeout(()=>{if(pending?.id!==id)return;pending=undefined;busy();persist();status(initial.strings.uncertain,true);},Math.max(1,30000-(Date.now()-(pending.at||Date.now()))));}
function send(action,payload={}){if(pending)return;const id=globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);pending={id,action,at:Date.now(),brief:payload.brief,personal:action==='personalize'?cleanPersonal(payload):undefined};persist();busy();status(initial.strings.waiting);vscode.postMessage({action,...payload,requestId:id});armTimeout();}
function validateBrief(requireGoal){const value=brief();if(value.goal.length>2000||value.audience.length>500||value.criteria.length>8||value.criteria.some(line=>line.length>300)){status(initial.strings.limits,true);byId('criteria').focus();return;}if(requireGoal&&!value.goal.trim()){status(initial.strings.goal,true);byId('goal').focus();return;}if(!initial.project){status(initial.strings.folder,true);return;}return value;}
fillBrief(cleanBrief(cached.brief||initial.brief));
// Keep the raw draft, including temporarily invalid lines, until the user edits it.
if(typeof cached.criteriaText==='string')byId('criteria').value=cached.criteriaText.slice(0,2407);
const initialPersonal=cleanPersonal(cached.personal||initial);byId('display-name').value=initialPersonal.displayName;document.querySelectorAll('input[name="experience"]').forEach(input=>input.checked=input.value===initialPersonal.experience);document.querySelectorAll('input[name="accent"]').forEach(input=>input.checked=input.value===initialPersonal.accent);
document.querySelectorAll('[data-tab]').forEach(button=>{button.addEventListener('click',()=>tab(button.dataset.tab));button.addEventListener('keydown',event=>{const tabs=['home','project','space'];let next=tabs.indexOf(currentTab);if(event.key==='ArrowRight')next=(next+1)%3;else if(event.key==='ArrowLeft')next=(next+2)%3;else if(event.key==='Home')next=0;else if(event.key==='End')next=2;else return;event.preventDefault();tab(tabs[next],true);});});
document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>{tab(button.dataset.go);byId('goal').focus();}));
document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>{const action=button.dataset.action;if(action==='profile'){send(action,{profile:button.dataset.profile});return;}vscode.postMessage({action});}));
document.querySelectorAll('#brief-form input,#brief-form textarea,#brief-form select,#personal-form input').forEach(input=>{input.addEventListener('input',update);input.addEventListener('change',update);});
byId('brief-form').addEventListener('submit',event=>{event.preventDefault();const value=validateBrief(false);if(value)send('saveBrief',{brief:value});});
byId('personal-form').addEventListener('submit',event=>{event.preventDefault();send('personalize',personal());});
document.querySelectorAll('[data-journey]').forEach(button=>button.addEventListener('click',()=>{const value=validateBrief(true);if(value)send('journey',{step:button.dataset.journey,brief:value});}));
function useStarter(index){const value=initial.starters[index];if(!value)return;fillBrief(cleanBrief(value));starter=undefined;byId('replacement').hidden=true;tab('project');update();status(initial.strings.replaced);byId('goal').focus();}
document.querySelectorAll('[data-starter]').forEach(button=>button.addEventListener('click',()=>{const value=brief(),index=Number(button.dataset.starter);tab('project');if(value.goal||value.audience||value.criteria.length){starter=index;byId('replacement').hidden=false;byId('cancel-starter').focus();}else useStarter(index);}));
byId('replace-starter').addEventListener('click',()=>useStarter(starter));byId('cancel-starter').addEventListener('click',()=>{starter=undefined;byId('replacement').hidden=true;byId('goal').focus();});
window.addEventListener('message',event=>{const message=event.data;if(!message||!['studioSaved','studioError'].includes(message.type)||!pending||message.requestId!==pending.id)return;const completed=pending;pending=undefined;clearTimeout(pendingTimer);if(message.type==='studioSaved'){if(completed.brief)savedBrief=cleanBrief(completed.brief);if(completed.personal)savedPersonal=cleanPersonal(completed.personal);const newer=completed.brief&&!same(brief(),savedBrief)||completed.personal&&!same(personal(),savedPersonal);status(newer?initial.strings.later:typeof message.message==='string'?message.message:'');if(completed.personal)byId('greeting').textContent=savedPersonal.displayName.trim()?initial.strings.greeting+savedPersonal.displayName.trim()+'.':initial.strings.welcome;}else status(typeof message.message==='string'?message.message:initial.strings.uncertain,true);busy();update();});
tab(currentTab);busy();update();armTimeout();
</script></body></html>`;
}
