import { AGENT_PROFILES, type AppLanguage } from '../agent/profiles';

const escape = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');

export function renderHome(nonce: string, language: AppLanguage, project?: string): string {
  if (!/^[A-Za-z0-9+/_=-]{16,128}$/.test(nonce)) throw new Error('Invalid nonce');
  const t = (es: string, en: string) => escape(language === 'en' ? en : es);
  const agents = AGENT_PROFILES.map(profile => `<button class="agent" data-action="profile" data-profile="${profile.id}"><span>${escape(profile.name[language])}</span><p>${escape(profile.description[language])}</p></button>`).join('');
  return `<!doctype html><html lang="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'; base-uri 'none'; form-action 'none';"><title>Caled</title>
  <style nonce="${nonce}">
  :root { color-scheme:light dark; --fg:var(--vscode-editor-foreground); --muted:var(--vscode-descriptionForeground); --line:var(--vscode-panel-border); --accent:var(--vscode-textLink-foreground); }
  * { box-sizing:border-box; } body { margin:0; background:var(--vscode-editor-background); color:var(--fg); font:14px/1.6 "Segoe UI Variable","Segoe UI",system-ui,sans-serif; }
  main { max-width:1080px; margin:auto; padding:32px clamp(24px,5vw,64px) 52px; } header { display:flex; align-items:center; gap:12px; padding-bottom:24px; border-bottom:1px solid var(--line); }
  .brand { font-size:26px; font-weight:600; letter-spacing:-1px; display:flex; align-items:center; gap:12px; } svg { width:34px; height:34px; color:var(--accent); }
  .top { margin-left:auto; display:flex; gap:8px; flex-wrap:wrap; justify-content:flex-end; } button { cursor:pointer; font:inherit; color:inherit; border:1px solid var(--line); background:transparent; border-radius:6px; padding:9px 15px; min-height:40px; } button:hover { background:var(--vscode-list-hoverBackground); } button:focus-visible { outline:2px solid var(--vscode-focusBorder); outline-offset:3px; }
  .eyebrow { font-size:11px; letter-spacing:1.6px; text-transform:uppercase; color:var(--accent); margin:42px 0 12px; }
  h1 { font-size:clamp(32px,4.8vw,54px); font-weight:550; letter-spacing:-1.9px; line-height:1.12; margin:0 0 20px; max-width:660px; } .lead { color:var(--muted); font-size:16px; max-width:600px; margin:0 0 25px; }
  .actions { display:flex; gap:10px; flex-wrap:wrap; } .primary { background:var(--vscode-button-background); color:var(--vscode-button-foreground); border-color:transparent; } .primary:hover { background:var(--vscode-button-hoverBackground); }
  .note { color:var(--muted); font-size:12px; margin-top:15px; } .section-title { display:flex; flex-wrap:wrap; align-items:baseline; gap:10px; margin-top:38px; } h2 { font-size:18px; font-weight:600; letter-spacing:-.35px; margin:0; } .section-title p { color:var(--muted); font-size:12px; margin:0; }
  .steps { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); margin:18px 0 0; gap:24px; padding:18px 0 22px; border-top:1px solid var(--line); border-bottom:1px solid var(--line); list-style:none; } .number { font:12px Consolas,monospace; color:var(--accent); display:block; margin-bottom:8px; } h3 { font-size:14px; font-weight:600; margin:0 0 6px; } .steps p { margin:0; color:var(--muted); font-size:13px; }
  .agents { display:grid; grid-template-columns:repeat(auto-fit,minmax(155px,1fr)); gap:10px; margin-top:18px; } .agent { text-align:left; padding:15px; align-self:stretch; } .agent span { font-weight:600; } .agent p { font-size:12px; color:var(--muted); line-height:1.6; margin:7px 0 0; }
  footer { color:var(--muted); font-size:12px; margin-top:30px; display:flex; justify-content:space-between; gap:15px; flex-wrap:wrap; } .status { color:var(--muted); min-height:24px; } @media(max-width:650px) { header { align-items:flex-start; } .steps { grid-template-columns:1fr; gap:18px; } .eyebrow { margin-top:28px; } .top button { font-size:12px; padding:6px 10px; } }
  @media(prefers-reduced-motion:reduce) { * { scroll-behavior:auto; } }
  </style></head><body><main>
  <header><div class="brand"><svg viewBox="0 0 64 64" aria-hidden="true" fill="none"><path d="M46 17a21 21 0 1 0 0 30" stroke="currentColor" stroke-width="7" stroke-linecap="round"/><path d="M30 32h26m-7-7 7 7-7 7" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></svg>caled</div><div class="top"><button data-action="preferences">${t('Idioma y apariencia', 'Language & appearance')}</button><button data-action="account">${t('Cuenta', 'Account')}</button></div></header>
  <p class="eyebrow">${t('Un espacio para tus ideas', 'A space for your ideas')}</p>
  <h1>${t('Empieza con lo que quieres crear.', 'Start with what you want to create.')}</h1>
  <p class="lead">${t('No necesitas tener todas las respuestas. Describe tu idea, entiende cada paso y construye con ayuda.', 'You do not need every answer. Describe your idea, understand each step and build with help.')}</p>
  <div class="actions"><button class="primary" data-action="${project ? 'assistant' : 'createProject'}">${project ? t('Continuar en ', 'Continue in ') + escape(project) : t('Crear mi primer proyecto', 'Create my first project')}</button><button data-action="openFolder">${project ? t('Abrir otro proyecto', 'Open another project') : t('Abrir un proyecto', 'Open a project')}</button><button data-action="${project ? 'createProject' : 'models'}">${project ? t('Crear un proyecto', 'Create a project') : t('Elegir mi modelo', 'Choose my model')}</button></div>
  <p class="note">${t('IA local sin cuota por token. Sin cuenta obligatoria. Tú eliges qué se aplica.', 'Local AI with no per-token fee. No account required. You choose what gets applied.')}</p>
  <div class="section-title"><h2>${t('Así trabajamos', 'How we work')}</h2></div>
  <ol class="steps"><li><span class="number">01</span><h3>${t('Cuenta tu idea', 'Describe your idea')}</h3><p>${t('“Quiero una página para mi negocio” o “Ayúdame a entender este error”. Habla con tus palabras.', '“I want a page for my business” or “Help me understand this error”. Use your own words.')}</p></li><li><span class="number">02</span><h3>${t('Revisa antes de cambiar', 'Review before changing')}</h3><p>${t('Verás qué archivos propone cambiar. Puedes aceptar, descartar o preguntar por qué.', 'See which files it proposes to change. Accept, decline or ask why.')}</p></li><li><span class="number">03</span><h3>${t('Comprueba y aprende', 'Check and learn')}</h3><p>${t('Autoriza las comprobaciones y lee el resultado. Los puntos de recuperación ayudan a volver atrás.', 'Approve checks and read their results. Recovery points help you go back.')}</p></li></ol>
  <div class="section-title"><h2>${t('La ayuda adecuada', 'The right kind of help')}</h2><p>${t('5 perfiles · una tarea a la vez', '5 profiles · one task at a time')}</p></div><div class="agents">${agents}</div>
  <footer><span>${t('Local por defecto. APIs externas opcionales.', 'Local by default. External APIs are optional.')}</span><span>${t('Consejo: pide que te expliquen cualquier paso.', 'Tip: ask for an explanation at any step.')}</span></footer><p id="status" class="status" role="status" aria-live="polite"></p>
  </main><script nonce="${nonce}">const vscode=acquireVsCodeApi(); let pending=false; document.querySelectorAll('button[data-action]').forEach(button=>button.addEventListener('click',()=>{if(pending)return;pending=true;vscode.postMessage({action:button.dataset.action,profile:button.dataset.profile});setTimeout(()=>{pending=false;},600);}));</script></body></html>`;
}
